// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fault.proto
#ifndef GRPC_fault_2eproto__INCLUDED
#define GRPC_fault_2eproto__INCLUDED

#include "fault.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace safemon {

class FaultService final {
 public:
  static constexpr char const* service_full_name() {
    return "safemon.FaultService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::safemon::FaultEvent>> StreamFaults(::grpc::ClientContext* context, const ::safemon::StreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::safemon::FaultEvent>>(StreamFaultsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::safemon::FaultEvent>> AsyncStreamFaults(::grpc::ClientContext* context, const ::safemon::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::safemon::FaultEvent>>(AsyncStreamFaultsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::safemon::FaultEvent>> PrepareAsyncStreamFaults(::grpc::ClientContext* context, const ::safemon::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::safemon::FaultEvent>>(PrepareAsyncStreamFaultsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamFaults(::grpc::ClientContext* context, const ::safemon::StreamRequest* request, ::grpc::ClientReadReactor< ::safemon::FaultEvent>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::safemon::FaultEvent>* StreamFaultsRaw(::grpc::ClientContext* context, const ::safemon::StreamRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::safemon::FaultEvent>* AsyncStreamFaultsRaw(::grpc::ClientContext* context, const ::safemon::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::safemon::FaultEvent>* PrepareAsyncStreamFaultsRaw(::grpc::ClientContext* context, const ::safemon::StreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::safemon::FaultEvent>> StreamFaults(::grpc::ClientContext* context, const ::safemon::StreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::safemon::FaultEvent>>(StreamFaultsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::safemon::FaultEvent>> AsyncStreamFaults(::grpc::ClientContext* context, const ::safemon::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::safemon::FaultEvent>>(AsyncStreamFaultsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::safemon::FaultEvent>> PrepareAsyncStreamFaults(::grpc::ClientContext* context, const ::safemon::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::safemon::FaultEvent>>(PrepareAsyncStreamFaultsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamFaults(::grpc::ClientContext* context, const ::safemon::StreamRequest* request, ::grpc::ClientReadReactor< ::safemon::FaultEvent>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::safemon::FaultEvent>* StreamFaultsRaw(::grpc::ClientContext* context, const ::safemon::StreamRequest& request) override;
    ::grpc::ClientAsyncReader< ::safemon::FaultEvent>* AsyncStreamFaultsRaw(::grpc::ClientContext* context, const ::safemon::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::safemon::FaultEvent>* PrepareAsyncStreamFaultsRaw(::grpc::ClientContext* context, const ::safemon::StreamRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamFaults_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamFaults(::grpc::ServerContext* context, const ::safemon::StreamRequest* request, ::grpc::ServerWriter< ::safemon::FaultEvent>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamFaults : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamFaults() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamFaults() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamFaults(::grpc::ServerContext* /*context*/, const ::safemon::StreamRequest* /*request*/, ::grpc::ServerWriter< ::safemon::FaultEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamFaults(::grpc::ServerContext* context, ::safemon::StreamRequest* request, ::grpc::ServerAsyncWriter< ::safemon::FaultEvent>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamFaults<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamFaults : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamFaults() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::safemon::StreamRequest, ::safemon::FaultEvent>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::safemon::StreamRequest* request) { return this->StreamFaults(context, request); }));
    }
    ~WithCallbackMethod_StreamFaults() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamFaults(::grpc::ServerContext* /*context*/, const ::safemon::StreamRequest* /*request*/, ::grpc::ServerWriter< ::safemon::FaultEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::safemon::FaultEvent>* StreamFaults(
      ::grpc::CallbackServerContext* /*context*/, const ::safemon::StreamRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StreamFaults<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamFaults : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamFaults() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamFaults() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamFaults(::grpc::ServerContext* /*context*/, const ::safemon::StreamRequest* /*request*/, ::grpc::ServerWriter< ::safemon::FaultEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamFaults : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamFaults() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamFaults() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamFaults(::grpc::ServerContext* /*context*/, const ::safemon::StreamRequest* /*request*/, ::grpc::ServerWriter< ::safemon::FaultEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamFaults(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamFaults : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamFaults() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamFaults(context, request); }));
    }
    ~WithRawCallbackMethod_StreamFaults() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamFaults(::grpc::ServerContext* /*context*/, const ::safemon::StreamRequest* /*request*/, ::grpc::ServerWriter< ::safemon::FaultEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamFaults(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamFaults : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamFaults() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::safemon::StreamRequest, ::safemon::FaultEvent>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::safemon::StreamRequest, ::safemon::FaultEvent>* streamer) {
                       return this->StreamedStreamFaults(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamFaults() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamFaults(::grpc::ServerContext* /*context*/, const ::safemon::StreamRequest* /*request*/, ::grpc::ServerWriter< ::safemon::FaultEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamFaults(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::safemon::StreamRequest,::safemon::FaultEvent>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamFaults<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_StreamFaults<Service > StreamedService;
};

}  // namespace safemon


#endif  // GRPC_fault_2eproto__INCLUDED
