// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fault.proto

#include "fault.pb.h"
#include "fault.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace safemon {

static const char* FaultService_method_names[] = {
  "/safemon.FaultService/StreamFaults",
};

std::unique_ptr< FaultService::Stub> FaultService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FaultService::Stub> stub(new FaultService::Stub(channel, options));
  return stub;
}

FaultService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamFaults_(FaultService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::safemon::FaultEvent>* FaultService::Stub::StreamFaultsRaw(::grpc::ClientContext* context, const ::safemon::StreamRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::safemon::FaultEvent>::Create(channel_.get(), rpcmethod_StreamFaults_, context, request);
}

void FaultService::Stub::async::StreamFaults(::grpc::ClientContext* context, const ::safemon::StreamRequest* request, ::grpc::ClientReadReactor< ::safemon::FaultEvent>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::safemon::FaultEvent>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamFaults_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::safemon::FaultEvent>* FaultService::Stub::AsyncStreamFaultsRaw(::grpc::ClientContext* context, const ::safemon::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::safemon::FaultEvent>::Create(channel_.get(), cq, rpcmethod_StreamFaults_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::safemon::FaultEvent>* FaultService::Stub::PrepareAsyncStreamFaultsRaw(::grpc::ClientContext* context, const ::safemon::StreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::safemon::FaultEvent>::Create(channel_.get(), cq, rpcmethod_StreamFaults_, context, request, false, nullptr);
}

FaultService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FaultService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< FaultService::Service, ::safemon::StreamRequest, ::safemon::FaultEvent>(
          [](FaultService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::safemon::StreamRequest* req,
             ::grpc::ServerWriter<::safemon::FaultEvent>* writer) {
               return service->StreamFaults(ctx, req, writer);
             }, this)));
}

FaultService::Service::~Service() {
}

::grpc::Status FaultService::Service::StreamFaults(::grpc::ServerContext* context, const ::safemon::StreamRequest* request, ::grpc::ServerWriter< ::safemon::FaultEvent>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace safemon

