# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fault.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66\x61ult.proto\x12\x07safemon\"\x0f\n\rStreamRequest\"R\n\nFaultEvent\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x11\n\tsignature\x18\x04 \x01(\t2M\n\x0c\x46\x61ultService\x12=\n\x0cStreamFaults\x12\x16.safemon.StreamRequest\x1a\x13.safemon.FaultEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fault_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STREAMREQUEST']._serialized_start=24
  _globals['_STREAMREQUEST']._serialized_end=39
  _globals['_FAULTEVENT']._serialized_start=41
  _globals['_FAULTEVENT']._serialized_end=123
  _globals['_FAULTSERVICE']._serialized_start=125
  _globals['_FAULTSERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
