// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fault.proto

#include "fault.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace safemon {
      template <typename>
PROTOBUF_CONSTEXPR StreamRequest::StreamRequest(::_pbi::ConstantInitialized) {}
struct StreamRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreamRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreamRequestDefaultTypeInternal() {}
  union {
    StreamRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreamRequestDefaultTypeInternal _StreamRequest_default_instance_;

inline constexpr FaultEvent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : status_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        source_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        signature_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FaultEvent::FaultEvent(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FaultEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FaultEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FaultEventDefaultTypeInternal() {}
  union {
    FaultEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FaultEventDefaultTypeInternal _FaultEvent_default_instance_;
}  // namespace safemon
static ::_pb::Metadata file_level_metadata_fault_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_fault_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_fault_2eproto = nullptr;
const ::uint32_t TableStruct_fault_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::safemon::StreamRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::safemon::FaultEvent, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::safemon::FaultEvent, _impl_.status_),
    PROTOBUF_FIELD_OFFSET(::safemon::FaultEvent, _impl_.timestamp_),
    PROTOBUF_FIELD_OFFSET(::safemon::FaultEvent, _impl_.source_),
    PROTOBUF_FIELD_OFFSET(::safemon::FaultEvent, _impl_.signature_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::safemon::StreamRequest)},
        {8, -1, -1, sizeof(::safemon::FaultEvent)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::safemon::_StreamRequest_default_instance_._instance,
    &::safemon::_FaultEvent_default_instance_._instance,
};
const char descriptor_table_protodef_fault_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\013fault.proto\022\007safemon\"\017\n\rStreamRequest\""
    "R\n\nFaultEvent\022\016\n\006status\030\001 \001(\t\022\021\n\ttimesta"
    "mp\030\002 \001(\003\022\016\n\006source\030\003 \001(\t\022\021\n\tsignature\030\004 "
    "\001(\t2M\n\014FaultService\022=\n\014StreamFaults\022\026.sa"
    "femon.StreamRequest\032\023.safemon.FaultEvent"
    "0\001b\006proto3"
};
static ::absl::once_flag descriptor_table_fault_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_fault_2eproto = {
    false,
    false,
    210,
    descriptor_table_protodef_fault_2eproto,
    "fault.proto",
    &descriptor_table_fault_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_fault_2eproto::offsets,
    file_level_metadata_fault_2eproto,
    file_level_enum_descriptors_fault_2eproto,
    file_level_service_descriptors_fault_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_fault_2eproto_getter() {
  return &descriptor_table_fault_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_fault_2eproto(&descriptor_table_fault_2eproto);
namespace safemon {
// ===================================================================

class StreamRequest::_Internal {
 public:
};

StreamRequest::StreamRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:safemon.StreamRequest)
}
StreamRequest::StreamRequest(
    ::google::protobuf::Arena* arena,
    const StreamRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  StreamRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:safemon.StreamRequest)
}









::google::protobuf::Metadata StreamRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fault_2eproto_getter, &descriptor_table_fault_2eproto_once,
      file_level_metadata_fault_2eproto[0]);
}
// ===================================================================

class FaultEvent::_Internal {
 public:
};

FaultEvent::FaultEvent(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:safemon.FaultEvent)
}
inline PROTOBUF_NDEBUG_INLINE FaultEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : status_(arena, from.status_),
        source_(arena, from.source_),
        signature_(arena, from.signature_),
        _cached_size_{0} {}

FaultEvent::FaultEvent(
    ::google::protobuf::Arena* arena,
    const FaultEvent& from)
    : ::google::protobuf::Message(arena) {
  FaultEvent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.timestamp_ = from._impl_.timestamp_;

  // @@protoc_insertion_point(copy_constructor:safemon.FaultEvent)
}
inline PROTOBUF_NDEBUG_INLINE FaultEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : status_(arena),
        source_(arena),
        signature_(arena),
        _cached_size_{0} {}

inline void FaultEvent::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timestamp_ = {};
}
FaultEvent::~FaultEvent() {
  // @@protoc_insertion_point(destructor:safemon.FaultEvent)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FaultEvent::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.status_.Destroy();
  _impl_.source_.Destroy();
  _impl_.signature_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FaultEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:safemon.FaultEvent)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_.ClearToEmpty();
  _impl_.source_.ClearToEmpty();
  _impl_.signature_.ClearToEmpty();
  _impl_.timestamp_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FaultEvent::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 48, 2> FaultEvent::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FaultEvent_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string signature = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(FaultEvent, _impl_.signature_)}},
    // string status = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FaultEvent, _impl_.status_)}},
    // int64 timestamp = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FaultEvent, _impl_.timestamp_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(FaultEvent, _impl_.timestamp_)}},
    // string source = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(FaultEvent, _impl_.source_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string status = 1;
    {PROTOBUF_FIELD_OFFSET(FaultEvent, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(FaultEvent, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string source = 3;
    {PROTOBUF_FIELD_OFFSET(FaultEvent, _impl_.source_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string signature = 4;
    {PROTOBUF_FIELD_OFFSET(FaultEvent, _impl_.signature_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\6\0\6\11\0\0\0"
    "safemon.FaultEvent"
    "status"
    "source"
    "signature"
  }},
};

::uint8_t* FaultEvent::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:safemon.FaultEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string status = 1;
  if (!this->_internal_status().empty()) {
    const std::string& _s = this->_internal_status();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "safemon.FaultEvent.status");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_timestamp(), target);
  }

  // string source = 3;
  if (!this->_internal_source().empty()) {
    const std::string& _s = this->_internal_source();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "safemon.FaultEvent.source");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string signature = 4;
  if (!this->_internal_signature().empty()) {
    const std::string& _s = this->_internal_signature();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "safemon.FaultEvent.signature");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safemon.FaultEvent)
  return target;
}

::size_t FaultEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safemon.FaultEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string status = 1;
  if (!this->_internal_status().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_status());
  }

  // string source = 3;
  if (!this->_internal_source().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_source());
  }

  // string signature = 4;
  if (!this->_internal_signature().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_signature());
  }

  // int64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FaultEvent::_class_data_ = {
    FaultEvent::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FaultEvent::GetClassData() const {
  return &_class_data_;
}

void FaultEvent::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FaultEvent*>(&to_msg);
  auto& from = static_cast<const FaultEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:safemon.FaultEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_status().empty()) {
    _this->_internal_set_status(from._internal_status());
  }
  if (!from._internal_source().empty()) {
    _this->_internal_set_source(from._internal_source());
  }
  if (!from._internal_signature().empty()) {
    _this->_internal_set_signature(from._internal_signature());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FaultEvent::CopyFrom(const FaultEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safemon.FaultEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FaultEvent::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FaultEvent::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FaultEvent::InternalSwap(FaultEvent* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.status_, &other->_impl_.status_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_, &other->_impl_.source_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.signature_, &other->_impl_.signature_, arena);
        swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

::google::protobuf::Metadata FaultEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fault_2eproto_getter, &descriptor_table_fault_2eproto_once,
      file_level_metadata_fault_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace safemon
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
