# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fault_pb2 as fault__pb2


class FaultServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFaults = channel.unary_stream(
                '/safemon.FaultService/StreamFaults',
                request_serializer=fault__pb2.StreamRequest.SerializeToString,
                response_deserializer=fault__pb2.FaultEvent.FromString,
                )


class FaultServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamFaults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFaults': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFaults,
                    request_deserializer=fault__pb2.StreamRequest.FromString,
                    response_serializer=fault__pb2.FaultEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'safemon.FaultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaultService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamFaults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/safemon.FaultService/StreamFaults',
            fault__pb2.StreamRequest.SerializeToString,
            fault__pb2.FaultEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
