BBPATH .= ":${LAYERDIR}"
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"
BBFILES_DYNAMIC += " \
    raspberrypi:${LAYERDIR}/recipes-bsp/bootfiles/*.bbappend \
"
BBFILE_COLLECTIONS += "meta-safemon"
BBFILE_PATTERN_meta-safemon = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-safemon = "6"
LAYERSERIES_COMPAT_meta-safemon = "scarthgap"
LAYERDEPENDS_meta-safemon = " \
    core \
    yocto \
    openembedded-layer \
    meta-python \
    networking-layer \
"