# Base on poky
require conf/distro/poky.conf

DISTRO = "safemon"
DISTRO_NAME = "Safemon Linux"
DISTRO_VERSION = "0.1"


# Systemd
DISTRO_FEATURES:append = " systemd usrmerge wifi"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
VIRTUAL-RUNTIME_login_manager = "shadow-base"

# SSH and debug
IMAGE_FEATURES += "ssh-server-openssh"
EXTRA_IMAGE_FEATURES += "debug-tweaks package-management"

# Wi-Fi firmware license
LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"

# Wi-Fi packages
IMAGE_INSTALL:append = " wpa-supplicant wpa-supplicant-config network-config linux-firmware-rpidistro-bcm43456"

IMAGE_INSTALL:append = " rt-tests"
# Redis
IMAGE_INSTALL:append = " redis hiredis safemon-app"

# GPU memory
RPI_GPU_MEM = "16"

# Kernel 6.12 with PREEMPT
PREFERRED_VERSION_linux-raspberrypi = "6.12%"
PREFERRED_PROVIDER_virtual/kernel = "linux-raspberrypi"
