# Base on poky
require conf/distro/poky.conf

DISTRO = "safemon-qemu"
DISTRO_NAME = "Safemon Linux QEMU"
DISTRO_VERSION = "0.1"

# Systemd
DISTRO_FEATURES:append = " systemd usrmerge opengl egl"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
VIRTUAL-RUNTIME_login_manager = "shadow-base"

# SSH and debug
IMAGE_FEATURES += "ssh-server-openssh"
EXTRA_IMAGE_FEATURES += "debug-tweaks package-management"

# Redis
IMAGE_INSTALL:append = " redis hiredis safemon-app"

# Graphics - Mesa with virgl (virtio-gpu guest driver)
IMAGE_INSTALL:append = " libdrm mesa mesa-megadriver"
PACKAGECONFIG:append:pn-mesa = " virgl"
