# Base on poky
require conf/distro/poky.conf

DISTRO = "safemon-qemu"
DISTRO_NAME = "Safemon Linux QEMU"
DISTRO_VERSION = "0.1"

# Systemd
DISTRO_FEATURES:append = " systemd usrmerge opengl egl"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
VIRTUAL-RUNTIME_login_manager = "shadow-base"

# SSH and debug
IMAGE_FEATURES += "ssh-server-openssh"
EXTRA_IMAGE_FEATURES += "debug-tweaks package-management"

IMAGE_INSTALL:append = " rt-tests"
# Redis
IMAGE_INSTALL:append = " redis hiredis safemon-app"
# CAN support
IMAGE_INSTALL:append = " can-utils vcan"
# Graphics - Mesa with virgl (virtio-gpu guest driver, no llvmpipe)
IMAGE_INSTALL:append = " libdrm mesa mesa-megadriver"
PACKAGECONFIG:append:pn-mesa = " virgl"
PACKAGECONFIG:remove:pn-mesa = "llvm"

IMAGE_INSTALL:append = " vim procps lsof strace"

IMAGE_INSTALL:append = " gmp openssl"

IMAGE_INSTALL:append = " grpc protobuf"

IMAGE_INSTALL:append = " abseil-cpp"
