# Base on poky
require conf/distro/poky.conf

DISTRO = "safemon-jetson"
DISTRO_NAME = "Safemon Linux Jetson"
DISTRO_VERSION = "0.1"

# Systemd
DISTRO_FEATURES:append = " systemd usrmerge wifi opengl egl"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
VIRTUAL-RUNTIME_login_manager = "shadow-base"

# SSH and debug
IMAGE_FEATURES += "ssh-server-openssh"
EXTRA_IMAGE_FEATURES += "debug-tweaks package-management"

# Wi-Fi packages (Jetson Orin Nano devkit uses M.2 Wi-Fi module)
IMAGE_INSTALL:append = " wpa-supplicant wpa-supplicant-config network-config"

IMAGE_INSTALL:append = " rt-tests"

# Redis
IMAGE_INSTALL:append = " redis hiredis safemon-app"

# CAN support
IMAGE_INSTALL:append = " can-utils vcan"

# Graphics
IMAGE_INSTALL:append = " libdrm libgbm"

IMAGE_INSTALL:append = " vim procps lsof strace"

IMAGE_INSTALL:append = " gmp openssl"

IMAGE_INSTALL:append = " grpc protobuf"

IMAGE_INSTALL:append = " abseil-cpp"

IMAGE_ROOTFS_SIZE = "2097152"
IMAGE_ROOTFS_EXTRA_SPACE = "524288"
